name: Deploy to local docker swarm on push
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose build
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: docker-compose push
      - name: Deploy stack
        run: docker stack deploy --compose-file docker-compose.yml --compose-file docker-compose.prod.yml --with-registry-auth --prune where-has-my-time-gone-api
